server:
  port: 10001

dubbo:
  #1、指定当前服务/应用的名字（同样的服务名字相同，不要和别的服务同名）
  application:
    name: consumer
    qos-enable: true
    qos-port: 33333
    qos-accept-foreign-ip: false
  #2、指定注册中心的位置
  registry:
    protocol: zookeeper
    address: 101.132.236.198:2181
  #3、指定通信规则（通信协议？通信端口）
  protocol:
    name: dubbo
    port: 20880
